[phases.setup]
nixPkgs = ["nodejs-18_x", "chromium"]

[phases.install]
cmds = [
  "npm install --prefix backend",
  "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "cd backend && node server.js"