[phases.setup]
nixPkgs = ["nodejs-18_x"]

[phases.install]
cmds = [
  "npm install --prefix backend --production",
  "npm install --prefix frontend"
]

[phases.build]
cmds = ["npm run build --prefix frontend"]

[start]
cmd = "npm start --prefix backend"